[phases.setup]
nixPkgs = ["bash"]

[phases.build]
cmds = [
  "dotnet restore WebAPI/WebAPI.csproj",
  "dotnet publish WebAPI/WebAPI.csproj -c Release -o /app/out /p:UseAppHost=false"
]

[start]
cmd = "sh -lc 'ASPNETCORE_URLS=http://0.0.0.0:$PORT dotnet /app/out/WebAPI.dll'"
